"use client";

import React, { useState } from 'react';
import { DashboardLayout } from '@/components/dashboard/DashboardLayout';
import Image from 'next/image';
import { CheckCircleIcon } from '@heroicons/react/24/solid';

// Sample data for carbon credit NFTs
const carbonProjects = [
  {
    id: 1,
    name: "Amazon Reforestation Project",
    certification: "Gold Standard Verified",
    vintage: "2023",
    icon: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 2,
    name: "Offshore Wind Farm",
    certification: "Verra Verified",
    vintage: "2023",
    icon: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 3,
    name: "Brazilian Forest Conservation",
    certification: "Verra Verified",
    vintage: "2024",
    icon: "https://images.unsplash.com/photo-1574263867128-58b5b8bee4f8?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 4,
    name: "Solar Energy Initiative",
    certification: "Gold Standard Verified",
    vintage: "2024",
    icon: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 5,
    name: "Coastal Wind Energy",
    certification: "Verra Verified",
    vintage: "2024",
    icon: "https://images.unsplash.com/photo-1548337138-e87d889cc369?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 6,
    name: "Ocean Conservation Project",
    certification: "Verra Verified",
    vintage: "2024",
    icon: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 7,
    name: "Sustainable Agriculture",
    certification: "Gold Standard Verified",
    vintage: "2023",
    icon: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 8,
    name: "Mountain Forest Protection",
    certification: "Verra Verified",
    vintage: "2023",
    icon: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=100&h=100&fit=crop&crop=center"
  },
  {
    id: 9,
    name: "Hydroelectric Power Plant",
    certification: "Gold Standard Verified",
    vintage: "2024",
    icon: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=100&h=100&fit=crop&crop=center"
  }
];

export default function RetirementPage() {
  const [selectedNFTs, setSelectedNFTs] = useState<number[]>([]);
  const [showCertificateModal, setShowCertificateModal] = useState(false);
  const [certificateOptions, setCertificateOptions] = useState({
    includeVerification: true,
    includeProjectDetails: true,
    certificateFormat: 'PDF',
    organizationName: '',
    retirementReason: ''
  });

  const toggleNFTSelection = (id: number) => {
    setSelectedNFTs(prev =>
      prev.includes(id)
        ? prev.filter(nftId => nftId !== id)
        : [...prev, id]
    );
  };

  const generateCertificate = () => {
    const selectedProjects = carbonProjects.filter(project => selectedNFTs.includes(project.id));
    const totalVolume = selectedProjects.length * 1000; // Simplified calculation
    
    const certificateData = {
      projects: selectedProjects,
      totalVolume,
      retirementDate: new Date().toISOString().split('T')[0],
      certificateId: `CARB-${Date.now()}`,
      ...certificateOptions,
      organizationName: certificateOptions.organizationName || 'Anonymous',
      retirementReason: certificateOptions.retirementReason || 'Carbon neutrality commitment'
    };

    // Create certificate content
    const certificateContent = `
CARBON CREDIT RETIREMENT CERTIFICATE

Certificate ID: ${certificateData.certificateId}
Retirement Date: ${certificateData.retirementDate}
Organization: ${certificateData.organizationName}
Retirement Reason: ${certificateData.retirementReason}

RETIRED PROJECTS:
${selectedProjects.map(project => `
- ${project.name}
  Certification: ${project.certification}
  Vintage: ${project.vintage}
  Volume: ~1,000 tCO2e
`).join('')}

Total Volume Retired: ${totalVolume} tCO2e

This certificate confirms the permanent retirement of the above carbon credits.
Credits have been removed from circulation and cannot be traded or transferred.

Generated by Carbonize DAPP - ${new Date().toLocaleString()}
`;

    // Download certificate as text file
    const blob = new Blob([certificateContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Carbon_Retirement_Certificate_${certificateData.certificateId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Reset state
    setSelectedNFTs([]);
    setShowCertificateModal(false);
    alert('Carbon credits retired successfully! Certificate downloaded.');
  };

  return (
    <DashboardLayout>
      <div className="min-h-screen bg-[#0B1220] text-white p-8">
        <h1 className="text-4xl font-bold mb-8">Retire Your Carbon Credits</h1>

        {/* Selection Section */}
        <div className="mb-8">
          <h2 className="text-xl text-gray-300 mb-4">Select NFTs to Retire</h2>
          <p className="text-gray-400 mb-8">
            Choose the carbon credits you wish to permanently retire.
          </p>

          {/* NFT Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {carbonProjects.map((project) => (
              <div
                key={project.id}
                onClick={() => toggleNFTSelection(project.id)}
                className={`relative bg-[#0D1522] border ${
                  selectedNFTs.includes(project.id)
                    ? 'border-green-500'
                    : 'border-gray-800'
                } rounded-lg p-6 cursor-pointer transition-all duration-200 hover:border-gray-700`}
              >
                <div className="flex items-start space-x-4">
                  <div className="relative w-12 h-12 flex-shrink-0">
                    <Image
                      src={project.icon}
                      alt={project.name}
                      fill
                      className="rounded-full object-cover"
                    />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold mb-2">{project.name}</h3>
                    <div className="space-y-1 text-gray-400">
                      <p>Certification: {project.certification}</p>
                      <p>Vintage: {project.vintage}</p>
                    </div>
                  </div>
                  {selectedNFTs.includes(project.id) && (
                    <CheckCircleIcon className="h-6 w-6 text-green-500 absolute top-4 right-4" />
                  )}
                </div>
                <button 
                  onClick={(e) => {
                    e.stopPropagation();
                    // Handle view details logic
                  }}
                  className="mt-4 text-gray-400 hover:text-white transition-colors text-sm"
                >
                  View Details
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Action Button */}
        <div className="flex justify-center mt-8">
          <button
            onClick={() => setShowCertificateModal(true)}
            disabled={selectedNFTs.length === 0}
            className={`px-8 py-3 rounded-lg text-white text-lg font-medium transition-all
              ${selectedNFTs.length === 0
                ? 'bg-gray-600 cursor-not-allowed opacity-50'
                : 'bg-green-500 hover:bg-green-600 transform hover:-translate-y-0.5'
              }`}
          >
            Review & Confirm Retirement
          </button>
        </div>

        {/* Disclaimer */}
        <p className="text-gray-400 text-sm text-center mt-6 max-w-2xl mx-auto">
          Please note that retiring carbon credits is a permanent action. Once retired, these credits cannot be traded or transferred.
        </p>

        {/* Certificate Modal */}
        {showCertificateModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-[#0D1522] border border-gray-800 rounded-xl p-8 max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
              <h2 className="text-2xl font-bold text-white mb-6">Generate Retirement Certificate</h2>
              
              <div className="space-y-6">
                {/* Organization Name */}
                <div>
                  <label className="block text-white text-sm font-medium mb-2">
                    Organization Name (Optional)
                  </label>
                  <input
                    type="text"
                    value={certificateOptions.organizationName}
                    onChange={(e) => setCertificateOptions(prev => ({
                      ...prev,
                      organizationName: e.target.value
                    }))}
                    className="w-full px-4 py-3 bg-[#0C1015] border border-gray-800 rounded-lg text-white focus:outline-none focus:border-green-500 transition-colors"
                    placeholder="Your organization name"
                  />
                </div>

                {/* Retirement Reason */}
                <div>
                  <label className="block text-white text-sm font-medium mb-2">
                    Retirement Reason (Optional)
                  </label>
                  <textarea
                    value={certificateOptions.retirementReason}
                    onChange={(e) => setCertificateOptions(prev => ({
                      ...prev,
                      retirementReason: e.target.value
                    }))}
                    rows={3}
                    className="w-full px-4 py-3 bg-[#0C1015] border border-gray-800 rounded-lg text-white focus:outline-none focus:border-green-500 transition-colors resize-none"
                    placeholder="e.g., Corporate carbon neutrality commitment"
                  />
                </div>

                {/* Certificate Options */}
                <div className="space-y-3">
                  <h3 className="text-white font-medium">Certificate Options</h3>
                  
                  <label className="flex items-center space-x-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={certificateOptions.includeVerification}
                      onChange={(e) => setCertificateOptions(prev => ({
                        ...prev,
                        includeVerification: e.target.checked
                      }))}
                      className="form-checkbox h-4 w-4 text-green-500 rounded border-gray-700 bg-transparent focus:ring-0"
                    />
                    <span className="text-gray-300">Include verification details</span>
                  </label>

                  <label className="flex items-center space-x-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={certificateOptions.includeProjectDetails}
                      onChange={(e) => setCertificateOptions(prev => ({
                        ...prev,
                        includeProjectDetails: e.target.checked
                      }))}
                      className="form-checkbox h-4 w-4 text-green-500 rounded border-gray-700 bg-transparent focus:ring-0"
                    />
                    <span className="text-gray-300">Include project details</span>
                  </label>
                </div>

                {/* Selected Projects Summary */}
                <div className="bg-[#0C1015] rounded-lg p-4">
                  <h4 className="text-white font-medium mb-3">Selected Projects for Retirement:</h4>
                  <div className="space-y-2">
                    {carbonProjects
                      .filter(project => selectedNFTs.includes(project.id))
                      .map((project) => (
                        <div key={project.id} className="flex justify-between items-center text-sm">
                          <span className="text-gray-300">{project.name}</span>
                          <span className="text-green-400">{project.certification}</span>
                        </div>
                      ))}
                  </div>
                  <div className="mt-3 pt-3 border-t border-gray-700">
                    <div className="flex justify-between items-center">
                      <span className="text-white font-medium">Total Projects:</span>
                      <span className="text-green-400 font-medium">{selectedNFTs.length}</span>
                    </div>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex space-x-4 pt-4">
                  <button
                    onClick={() => setShowCertificateModal(false)}
                    className="flex-1 px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white rounded-lg transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={generateCertificate}
                    className="flex-1 px-6 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors font-medium"
                  >
                    Generate Certificate & Retire
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}